//
//  HomeTableViewController.swift
//  Periodic Table
//
//  Created by sean on 30/6/18.
//  Copyright © 2018 sean. All rights reserved.
//

import UIKit
var elementarray = [["    Hydrogen    "    ,
                     "    Helium    "    ,
                     "    Lithium    "    ,
                     "    Beryllium    "    ,
                     "    Boron    "    ,
                     "    Carbon    "    ,
                     "    Nitrogen    "    ,
                     "    Oxygen    "    ,
                     "    Fluorine    "    ,
                     "    Neon    "    ,
                     "    Sodium    "    ,
                     "    Magnesium    "    ,
                     "    Aluminium    "    ,
                     "    Silicon    "    ,
                     "    Phosphorus    "    ,
                     "    Sulfur    "    ,
                     "    Chlorine    "    ,
                     "    Argon    "    ,
                     "    Potassium    "    ,
                     "    Calcium    "    ,
                     "    Scandium    "    ,
                     "    Titanium    "    ,
                     "    Vanadium    "    ,
                     "    Chromium    "    ,
                     "    Manganese    "    ,
                     "    Iron    "    ,
                     "    Cobalt    "    ,
                     "    Nickel    "    ,
                     "    Copper    "    ,
                     "    Zinc    "    ,
                     "    Gallium    "    ,
                     "    Germanium    "    ,
                     "    Arsenic    "    ,
                     "    Selenium    "    ,
                     "    Bromine    "    ,
                     "    Krypton    "    ,
                     "    Rubidium    "    ,
                     "    Strontium    "    ,
                     "    Yttrium    "    ,
                     "    Zirconium    "    ,
                     "    Niobium    "    ,
                     "    Molybdenum    "    ,
                     "    Technetium    "    ,
                     "    Ruthenium    "    ,
                     "    Rhodium    "    ,
                     "    Palladium    "    ,
                     "    Silver    "    ,
                     "    Cadmium    "    ,
                     "    Indium    "    ,
                     "    Tin    "    ,
                     "    Antimony    "    ,
                     "    Tellurium    "    ,
                     "    Iodine    "    ,
                     "    Xenon    "    ,
                     "    Cesium    "    ,
                     "    Barium    "    ,
                     "    Lanthanum    "    ,
                     "    Cerium    "    ,
                     "    Praseodymium    "    ,
                     "    Neodymium    "    ,
                     "    Promethium    "    ,
                     "    Samarium    "    ,
                     "    Europium    "    ,
                     "    Gadolinium    "    ,
                     "    Terbium    "    ,
                     "    Dysprosium    "    ,
                     "    Holmium    "    ,
                     "    Erbium    "    ,
                     "    Thulium    "    ,
                     "    Ytterbium    "    ,
                     "    Lutetium    "    ,
                     "    Hafnium    "    ,
                     "    Tantalum    "    ,
                     "    Tungsten    "    ,
                     "    Rhenium    "    ,
                     "    Osmium    "    ,
                     "    Iridium    "    ,
                     "    Platinum    "    ,
                     "    Gold    "    ,
                     "    Mercury    "    ,
                     "    Thallium    "    ,
                     "    Lead    "    ,
                     "    Bismuth    "    ,
                     "    Polonium    "    ,
                     "    Astatine    "    ,
                     "    Radon    "    ,
                     "    Francium    "    ,
                     "    Radium    "    ,
                     "    Actinium    "    ,
                     "    Thorium    "    ,
                     "    Protactinium    "    ,
                     "    Uranium    "    ,
                     "    Neptunium    "    ,
                     "    Plutonium    "    ,
                     "    Americium    "    ,
                     "    Curium    "    ,
                     "    Berkelium    "    ,
                     "    Californium    "    ,
                     "    Einsteinium    "    ,
                     "    Fermium    "    ,
                     "    Mendelevium    "    ,
                     "    Nobelium    "    ,
                     "    Lawrencium    "    ,
                     "    Rutherfordium    "    ,
                     "    Dubnium    "    ,
                     "    Seaborgium    "    ,
                     "    Bohrium    "    ,
                     "    Hassium    "    ,
                     "    Meitnerium    "    ,
                     "    Darmstadtium    "    ,
                     "    Roentgenium    "    ,
                     "    Copernicium    "    ,
                     "    Nihonium    "    ,
                     "    Flerovium    "    ,
                     "    Moscovium    "    ,
                     "    Livermorium    "    ,
                     "    Tennessine    "    ,
                     "    Oganesson    "
    ],["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""],["    Hidrogen    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Helium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Litium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Berilium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Boron    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Karbon    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Nitrogen    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Oksigen    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Fluorin    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Neon    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Natrium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Magnesium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Aluminium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Silikon    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Fosforus    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Sulfur    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Klorin    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Argon    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kalium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kalsium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Skandium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Titanium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Vanadium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kromium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Mangan    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ferum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kobalt    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Nikel    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kuprum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Zink    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Galium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Germanium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Arsenik    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Selenium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Bromin    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Krypton    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Rubidium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Strontium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ytrium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Zirkonium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Niobium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Molibdenum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Teknetium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Rutenium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Rodium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Paladium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Argentum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kadmium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Indium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Timah    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Antimoni    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Telurium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Iodin    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Xenon    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Sesium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Barium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Lantanum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Serium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Praseodimium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Neodimium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Promethium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Samarium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Europium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Gadolinium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Terbium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Disprosium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Holmium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Erbium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Thulium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Yterbium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Lutetium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Hafnium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Tantalum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Tungsten    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Rhenium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Osmium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Iridium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Platinum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Aurum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Raksa    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Talium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Plumbum    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Bismut    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Polonium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Astatin    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Radon    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Fransium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Radium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Aktinium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Torium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Protaktinium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Uranium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Neptunium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Plutonium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Amerisium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kurium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Berkelium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Kalifornium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Einsteinium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Fermium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Mendelevium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Nobelium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Lawrensium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Rutherfordium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Dubnium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Seaborgium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Bohrium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Hassium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Meitnerium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Darmstadtium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Roentgenium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununbium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununtrium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununquadium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununpentium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununhexium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununseptium    "    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "    Ununoctium    "    ],["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""],["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]]
class HomeTableViewController: UITableViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor(red: 0, green: 107, blue: 255, alpha: 1)
        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    // MARK: - Table view data source

    override func numberOfSections(in tableView: UITableView) -> Int {
        // #warning Incomplete implementation, return the number of sections
        return 1
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // #warning Incomplete implementation, return the number of rows
        return (elementarray[0].count)-1
        
    }

    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "First", for: indexPath)
        
        // Configure the cell...
        var first = UILabel()
        first.text = elementarray[1][indexPath.row]
        print(indexPath.row)
        first.textAlignment = .center
        first.frame = CGRect(x: Int(UIScreen.main.bounds.width)/5+30, y: 0, width: Int(UIScreen.main.bounds.width / 5), height: 50)
        cell.addSubview(first)
        
        var second = UILabel()
        second.text = elementarray[2][indexPath.row]
        second.frame = CGRect(x: ((Int(UIScreen.main.bounds.width))/5*2+10) , y: -5, width: Int(UIScreen.main.bounds.width / 5), height: 50)
        second.textAlignment = .center
        cell.addSubview(second)
        
        var third = UILabel()
        third.text = elementarray[3][indexPath.row]
        third.frame = CGRect(x: ((Int(UIScreen.main.bounds.width))/5*3) , y: 0, width: Int(UIScreen.main.bounds.width / 5), height: 50)
        third.textAlignment = .center
        cell.addSubview(third)
        
        var fourth = UILabel()
        fourth.text = elementarray[4][indexPath.row]
        fourth.frame = CGRect(x: ((Int(UIScreen.main.bounds.width))/5*2) , y: 0, width: Int(UIScreen.main.bounds.width / 5), height: 50)
        fourth.textAlignment = .center
        cell.addSubview(fourth)
        


        if let label = cell.textLabel {
            let curr = elementarray[0][indexPath.row]
            label.frame = CGRect(x: -5, y: 0, width: UIScreen.main.bounds.width / 5, height: 50)
            label.text = String(curr)
            label.font.withSize(2)
        
            
        }
        return cell
    }
    

    /*
    // Override to support conditional editing of the table view.
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the specified item to be editable.
        return true
    }
    */

    /*
    // Override to support editing the table view.
    override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            // Delete the row from the data source
            tableView.deleteRows(at: [indexPath], with: .fade)
        } else if editingStyle == .insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
        }    
    }
    */

    /*
    // Override to support rearranging the table view.
    override func tableView(_ tableView: UITableView, moveRowAt fromIndexPath: IndexPath, to: IndexPath) {

    }
    */

    /*
    // Override to support conditional rearranging of the table view.
    override func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the item to be re-orderable.
        return true
    }
    */

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
